export const settings = {
  gender: [
    { value: 'masculino', label: 'Masculino' },
    { value: 'femenino', label: 'Femenino' },
    { value: 'transgénero', label: 'Transgénero' },
    { value: 'no_binario', label: 'No binario' },
    { value: 'genero_fluido', label: 'Género fluido' },
    { value: 'bigénero', label: 'Bigénero' },
    { value: 'agénero', label: 'Agénero' },
    { value: 'androginia', label: 'Androginia' },
    { value: 'genderqueer', label: 'Genderqueer' },
    { value: 'pansexual', label: 'Pansexual' },
    { value: 'intersexual', label: 'Intersexual' },
  ],
  types: [
    { value: 'tradicional', label: 'Tradicional' },
    { value: 'geométrico', label: 'Geométrico' },
    { value: 'realista', label: 'Realista' },
    { value: 'acuarela', label: 'Acuarela' },
    { value: 'neo-tradicional', label: 'Neo-tradicional' },
    { value: 'minimalista', label: 'Minimalista' },
    { value: 'trash-polka', label: 'Trash Polka' },
    { value: 'blackwork', label: 'Blackwork' },
    { value: 'fineline', label: 'Fineline' },
    { value: 'dotwork', label: 'Dotwork' },
    { value: 'new-school', label: 'New School' },
    { value: 'japonés', label: 'Japonés (Irezumi)' },
    { value: 'biomecánico', label: 'Biomecánico' },
    { value: 'tatuaje-glow-in-the-dark', label: 'Glow in the Dark' },
    { value: 'efecto-3d', label: 'Efecto 3D' },
    { value: 'neotradicional', label: 'Neotradicional' },
    { value: 'estilo-chicano', label: 'Estilo Chicano' },
    { value: 'tatuaje-escritura', label: 'Escritura (Lettering)' },
    { value: 'tatuaje-flechas', label: 'Flechas' },
    { value: 'tatuaje-tribal', label: 'Tribal' },
  ],
};
